name: hexlet CI app

on:
  - push
  - pull_request

jobs:

  build:
    
    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cash: 'npm'

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - run: make setup
      - run: make test
      - run: make lint
